FROM python:3.11-slim AS base

WORKDIR /app

COPY app/ app/
COPY tests/ tests/

COPY requirements.txt .

RUN pip install -r requirements.txt

ENV FLASK_ENV=test

RUN pip install pytest

CMD ["sh", "-c", "echo Waiting 5 seconds... && sleep 10 && pytest tests && rm -rf /app"]
